//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.03 at 04:46:12 PM SGT 
//


package com.vcc.camelone.eco.exchange.source.fti.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CertificateOfOrigin }
     * 
     */
    public CertificateOfOrigin createCertificateOfOrigin() {
        return new CertificateOfOrigin();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.IssuerEndorsement }
     * 
     */
    public CertificateOfOrigin.IssuerEndorsement createCertificateOfOriginIssuerEndorsement() {
        return new CertificateOfOrigin.IssuerEndorsement();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.IssuerEndorsement.EndorserParty }
     * 
     */
    public CertificateOfOrigin.IssuerEndorsement.EndorserParty createCertificateOfOriginIssuerEndorsementEndorserParty() {
        return new CertificateOfOrigin.IssuerEndorsement.EndorserParty();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party }
     * 
     */
    public CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party createCertificateOfOriginIssuerEndorsementEndorserPartyParty() {
        return new CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.Address }
     * 
     */
    public CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.Address createCertificateOfOriginIssuerEndorsementEndorserPartyPartyAddress() {
        return new CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.Address();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication createCertificateOfOriginCertificateofOriginApplication() {
        return new CertificateOfOrigin.CertificateofOriginApplication();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.IssuerParty }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.IssuerParty createCertificateOfOriginCertificateofOriginApplicationIssuerParty() {
        return new CertificateOfOrigin.CertificateofOriginApplication.IssuerParty();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.PreparationParty }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.PreparationParty createCertificateOfOriginCertificateofOriginApplicationPreparationParty() {
        return new CertificateOfOrigin.CertificateofOriginApplication.PreparationParty();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment createCertificateOfOriginCertificateofOriginApplicationShipment() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.OriginAddress }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.OriginAddress createCertificateOfOriginCertificateofOriginApplicationShipmentOriginAddress() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.OriginAddress();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnit() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackage() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackageGoodsItem() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.InvoiceLine }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.InvoiceLine createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackageGoodsItemInvoiceLine() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.InvoiceLine();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStage() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStageUnloadingPortLocation() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation.Address }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation.Address createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStageUnloadingPortLocationAddress() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation.Address();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStageLoadingPortLocation() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation.Address }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation.Address createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStageLoadingPortLocationAddress() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation.Address();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.TransportMeans }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.TransportMeans createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStageTransportMeans() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.TransportMeans();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment createCertificateOfOriginCertificateofOriginApplicationShipmentConsignment() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentImporterParty() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.Address }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.Address createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentImporterPartyAddress() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.Address();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentExporterParty() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.Address }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.Address createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentExporterPartyAddress() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.Address();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.EndorserParty }
     * 
     */
    public CertificateOfOrigin.EndorserParty createCertificateOfOriginEndorserParty() {
        return new CertificateOfOrigin.EndorserParty();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.EndorserParty.Party }
     * 
     */
    public CertificateOfOrigin.EndorserParty.Party createCertificateOfOriginEndorserPartyParty() {
        return new CertificateOfOrigin.EndorserParty.Party();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.PartyIdentification }
     * 
     */
    public CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.PartyIdentification createCertificateOfOriginIssuerEndorsementEndorserPartyPartyPartyIdentification() {
        return new CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.PartyIdentification();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.PartyName }
     * 
     */
    public CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.PartyName createCertificateOfOriginIssuerEndorsementEndorserPartyPartyPartyName() {
        return new CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.PartyName();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.Address.AddressLine }
     * 
     */
    public CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.Address.AddressLine createCertificateOfOriginIssuerEndorsementEndorserPartyPartyAddressAddressLine() {
        return new CertificateOfOrigin.IssuerEndorsement.EndorserParty.Party.Address.AddressLine();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.IssuingCountry }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.IssuingCountry createCertificateOfOriginCertificateofOriginApplicationIssuingCountry() {
        return new CertificateOfOrigin.CertificateofOriginApplication.IssuingCountry();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.SupportingDocumentReference }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.SupportingDocumentReference createCertificateOfOriginCertificateofOriginApplicationSupportingDocumentReference() {
        return new CertificateOfOrigin.CertificateofOriginApplication.SupportingDocumentReference();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.IssuerParty.PartyName }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.IssuerParty.PartyName createCertificateOfOriginCertificateofOriginApplicationIssuerPartyPartyName() {
        return new CertificateOfOrigin.CertificateofOriginApplication.IssuerParty.PartyName();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.PreparationParty.PartyName }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.PreparationParty.PartyName createCertificateOfOriginCertificateofOriginApplicationPreparationPartyPartyName() {
        return new CertificateOfOrigin.CertificateofOriginApplication.PreparationParty.PartyName();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TotalGoodsItemQuantity }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TotalGoodsItemQuantity createCertificateOfOriginCertificateofOriginApplicationShipmentTotalGoodsItemQuantity() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TotalGoodsItemQuantity();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.DeclaredCustomsValueAmount }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.DeclaredCustomsValueAmount createCertificateOfOriginCertificateofOriginApplicationShipmentDeclaredCustomsValueAmount() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.DeclaredCustomsValueAmount();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.OriginAddress.Country }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.OriginAddress.Country createCertificateOfOriginCertificateofOriginApplicationShipmentOriginAddressCountry() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.OriginAddress.Country();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.ValueAmount }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.ValueAmount createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackageGoodsItemValueAmount() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.ValueAmount();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.GrossWeightMeasure }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.GrossWeightMeasure createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackageGoodsItemGrossWeightMeasure() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.GrossWeightMeasure();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.NetWeightMeasure }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.NetWeightMeasure createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackageGoodsItemNetWeightMeasure() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.NetWeightMeasure();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.GrossVolumeMeasure }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.GrossVolumeMeasure createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackageGoodsItemGrossVolumeMeasure() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.GrossVolumeMeasure();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.QuantityNumeric }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.QuantityNumeric createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackageGoodsItemQuantityNumeric() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.QuantityNumeric();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.InvoiceLine.Item }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.InvoiceLine.Item createCertificateOfOriginCertificateofOriginApplicationShipmentTransportHandlingUnitActualPackageGoodsItemInvoiceLineItem() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.TransportHandlingUnit.ActualPackage.GoodsItem.InvoiceLine.Item();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation.Address.Country }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation.Address.Country createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStageUnloadingPortLocationAddressCountry() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.UnloadingPortLocation.Address.Country();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation.Address.Country }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation.Address.Country createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStageLoadingPortLocationAddressCountry() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.LoadingPortLocation.Address.Country();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.TransportMeans.MaritimeTransport }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.TransportMeans.MaritimeTransport createCertificateOfOriginCertificateofOriginApplicationShipmentShipmentStageTransportMeansMaritimeTransport() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.ShipmentStage.TransportMeans.MaritimeTransport();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.TotalInvoiceAmount }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.TotalInvoiceAmount createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentTotalInvoiceAmount() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.TotalInvoiceAmount();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.NetWeightMeasure }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.NetWeightMeasure createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentNetWeightMeasure() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.NetWeightMeasure();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.GrossVolumeMeasure }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.GrossVolumeMeasure createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentGrossVolumeMeasure() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.GrossVolumeMeasure();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.PartyIdentification }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.PartyIdentification createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentImporterPartyPartyIdentification() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.PartyIdentification();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.Address.AddressLine }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.Address.AddressLine createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentImporterPartyAddressAddressLine() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ImporterParty.Address.AddressLine();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.PartyIdentification }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.PartyIdentification createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentExporterPartyPartyIdentification() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.PartyIdentification();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.PartyName }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.PartyName createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentExporterPartyPartyName() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.PartyName();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.Address.AddressLine }
     * 
     */
    public CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.Address.AddressLine createCertificateOfOriginCertificateofOriginApplicationShipmentConsignmentExporterPartyAddressAddressLine() {
        return new CertificateOfOrigin.CertificateofOriginApplication.Shipment.Consignment.ExporterParty.Address.AddressLine();
    }

    /**
     * Create an instance of {@link CertificateOfOrigin.EndorserParty.Party.PartyIdentification }
     * 
     */
    public CertificateOfOrigin.EndorserParty.Party.PartyIdentification createCertificateOfOriginEndorserPartyPartyPartyIdentification() {
        return new CertificateOfOrigin.EndorserParty.Party.PartyIdentification();
    }

}
